package com.ngsmusic.visualizer

import android.content.ContentValues
import android.content.Context
import android.graphics.Bitmap
import android.media.*
import android.net.Uri
import android.os.Environment
import android.provider.MediaStore
import java.io.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.max
import kotlin.math.min

object VideoExporter {
 data class Spec(val ratioIndex:Int,val qualityIndex:Int,val fps:Int,val styleIndex:Int,val colorIndex:Int,val intensity:Float=1f){
  val size:Pair<Int,Int> get(){val base=when(qualityIndex){2->2160 to 3840;1->1440 to 2560;else->1080 to 1920};return when(ratioIndex){1->base.second to base.first;2->base.first to base.first;else->base}}
 }
 fun export(context:Context,audioUri:Uri,background:Bitmap?,logo:Bitmap?,spectrum:SpectrumData,spec:Spec,onProgress:(Int,String)->Unit):Uri{
  val dir=File(context.cacheDir,"ngs_visualizer_export").apply{mkdirs()};val s=System.currentTimeMillis();val v=File(dir,"v$s.mp4");val p=File(dir,"a$s.pcm");val a=File(dir,"a$s.mp4");val f=File(dir,"f$s.mp4")
  try{onProgress(1,"Chuẩn bị encoder video…");encodeVideo(v,background,logo,spectrum,spec){onProgress((it*.82f).toInt().coerceIn(1,82),"Đang render video $it%")};onProgress(83,"Đang xử lý âm thanh…");val pcm=decodeAudioToPcm(context,audioUri,p){onProgress(83+(it*.05f).toInt(),"Đang giải mã audio…")};encodePcmToAac(pcm,a){onProgress(88+(it*.07f).toInt(),"Đang mã hóa AAC…")};onProgress(96,"Đang ghép MP4…");mux(v,a,f);onProgress(98,"Đang lưu vào thư viện…");return save(context,f,spec).also{onProgress(100,"Hoàn tất")}}
  finally{listOf(v,p,a,f).forEach{runCatching{it.delete()}}}
 }
 private fun encodeVideo(output:File,bg:Bitmap?,logo:Bitmap?,sp:SpectrumData,spec:Spec,progress:(Int)->Unit){
  val(width,height)=spec.size;val fps=spec.fps.coerceIn(24,60);val dur=sp.durationUs.coerceAtLeast(1_000_000);val frames=max(1L,(dur*fps+999999)/1_000_000);val base=when{max(width,height)>=3800->56_000_000;max(width,height)>=2500->30_000_000;else->16_000_000};val rate=if(fps>=60)base else (base*.72f).toInt();val choice=chooseEncoder(width,height,fps,rate)
  val format=MediaFormat.createVideoFormat(choice.mime,width,height).apply{setInteger(MediaFormat.KEY_COLOR_FORMAT,MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);setInteger(MediaFormat.KEY_BIT_RATE,choice.rate);setInteger(MediaFormat.KEY_FRAME_RATE,fps);setInteger(MediaFormat.KEY_I_FRAME_INTERVAL,1);runCatching{setInteger(MediaFormat.KEY_BITRATE_MODE,MediaCodecInfo.EncoderCapabilities.BITRATE_MODE_VBR)}}
  val codec=MediaCodec.createByCodecName(choice.name);var muxer:MediaMuxer?=null;var egl:EncoderEglSurface?=null;var renderer:GlVisualizerRenderer?=null
  try{codec.configure(format,null,null,MediaCodec.CONFIGURE_FLAG_ENCODE);val surface=codec.createInputSurface();codec.start();egl=EncoderEglSurface(surface);renderer=GlVisualizerRenderer(width,height,bg,logo,sp,spec.styleIndex,spec.colorIndex,spec.intensity);muxer=MediaMuxer(output.absolutePath,MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);val info=MediaCodec.BufferInfo();var track=-1;var started=false;var frame=0L;var last=-1
   fun drain(wait:Boolean):Boolean{var eos=false;while(true){when(val idx=codec.dequeueOutputBuffer(info,if(wait)20000 else 0)){MediaCodec.INFO_TRY_AGAIN_LATER->return eos;MediaCodec.INFO_OUTPUT_FORMAT_CHANGED->{if(!started){track=muxer!!.addTrack(codec.outputFormat);muxer!!.start();started=true}};else->if(idx>=0){val b=codec.getOutputBuffer(idx);if(b!=null&&info.size>0&&started&&(info.flags and MediaCodec.BUFFER_FLAG_CODEC_CONFIG)==0){b.position(info.offset);b.limit(info.offset+info.size);muxer!!.writeSampleData(track,b,info)};eos=(info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM)!=0;codec.releaseOutputBuffer(idx,false);if(eos)return true}}}}
   while(frame<frames){val us=frame*1_000_000/fps;renderer.draw(us/1000);egl.setPresentationTime(us*1000);require(egl.swapBuffers());drain(false);frame++;val pp=(frame*100/frames).toInt().coerceIn(0,99);if(pp!=last){last=pp;progress(pp)}};codec.signalEndOfInputStream();while(!drain(true)){};progress(100)
  }catch(e:Throwable){throw IllegalStateException("Thiết bị không render được ${width}x${height} ${fps}fps. Hãy thử 2K/1080p hoặc 30fps. Chi tiết: ${e.message}",e)}finally{runCatching{renderer?.release()};runCatching{egl?.release()};runCatching{codec.stop()};runCatching{codec.release()};runCatching{muxer?.stop()};runCatching{muxer?.release()}}
 }
 private data class VC(val name:String,val mime:String,val rate:Int)
 private fun chooseEncoder(w:Int,h:Int,fps:Int,rate:Int):VC{val list=MediaCodecList(MediaCodecList.REGULAR_CODECS);for((mime,r) in listOf(MediaFormat.MIMETYPE_VIDEO_AVC to rate,MediaFormat.MIMETYPE_VIDEO_HEVC to (rate*.72f).toInt())){val f=MediaFormat.createVideoFormat(mime,w,h).apply{setInteger(MediaFormat.KEY_COLOR_FORMAT,MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);setInteger(MediaFormat.KEY_BIT_RATE,r);setInteger(MediaFormat.KEY_FRAME_RATE,fps)};val name=runCatching{list.findEncoderForFormat(f)}.getOrNull();if(!name.isNullOrBlank())return VC(name,mime,r)};error("Không tìm thấy encoder H.264/HEVC phù hợp cho ${w}x${h}@${fps}.")}
 private data class PCM(val file:File,val rate:Int,val channels:Int)
 private fun decodeAudioToPcm(context:Context,uri:Uri,output:File,progress:(Int)->Unit):PCM{
  val ex=MediaExtractor();var dec:MediaCodec?=null;var out:BufferedOutputStream?=null
  try{ex.setDataSource(context,uri,null);var tr=-1;var fmt:MediaFormat?=null;for(i in 0 until ex.trackCount){val f=ex.getTrackFormat(i);if(f.getString(MediaFormat.KEY_MIME).orEmpty().startsWith("audio/")){tr=i;fmt=f;break}};require(tr>=0&&fmt!=null);ex.selectTrack(tr);val input=fmt!!;val mime=input.getString(MediaFormat.KEY_MIME)?:error("Audio MIME lỗi");val dur=if(input.containsKey(MediaFormat.KEY_DURATION))input.getLong(MediaFormat.KEY_DURATION)else 0;var rate=input.getInteger(MediaFormat.KEY_SAMPLE_RATE);var ch=input.getInteger(MediaFormat.KEY_CHANNEL_COUNT);var enc=AudioFormat.ENCODING_PCM_16BIT;runCatching{input.setInteger(MediaFormat.KEY_PCM_ENCODING,enc)};dec=MediaCodec.createDecoderByType(mime);dec.configure(input,null,null,0);dec.start();out=BufferedOutputStream(FileOutputStream(output),262144);val info=MediaCodec.BufferInfo();var inDone=false;var done=false;var last=-1;var outCh=min(2,max(1,ch))
   while(!done){if(!inDone){val i=dec.dequeueInputBuffer(10000);if(i>=0){val b=dec.getInputBuffer(i)!!;val n=ex.readSampleData(b,0);if(n<0){dec.queueInputBuffer(i,0,0,0,MediaCodec.BUFFER_FLAG_END_OF_STREAM);inDone=true}else{val pts=ex.sampleTime.coerceAtLeast(0);dec.queueInputBuffer(i,0,n,pts,ex.sampleFlags);ex.advance();if(dur>0){val p=(pts*100/dur).toInt().coerceIn(0,99);if(p!=last){last=p;progress(p)}}}}};when(val i=dec.dequeueOutputBuffer(info,10000)){MediaCodec.INFO_TRY_AGAIN_LATER->Unit;MediaCodec.INFO_OUTPUT_FORMAT_CHANGED->{val f=dec.outputFormat;if(f.containsKey(MediaFormat.KEY_SAMPLE_RATE))rate=f.getInteger(MediaFormat.KEY_SAMPLE_RATE);if(f.containsKey(MediaFormat.KEY_CHANNEL_COUNT))ch=f.getInteger(MediaFormat.KEY_CHANNEL_COUNT);if(f.containsKey(MediaFormat.KEY_PCM_ENCODING))enc=f.getInteger(MediaFormat.KEY_PCM_ENCODING);outCh=min(2,max(1,ch))};else->if(i>=0){val b=dec.getOutputBuffer(i);if(b!=null&&info.size>0)writePcm16(b,info.offset,info.size,max(1,ch),outCh,enc,out);done=(info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM)!=0;dec.releaseOutputBuffer(i,false)}}};out.flush();progress(100);return PCM(output,rate,outCh)
  }finally{runCatching{out?.close()};runCatching{dec?.stop()};runCatching{dec?.release()};runCatching{ex.release()}}
 }
 private fun writePcm16(src:ByteBuffer,offset:Int,size:Int,inCh:Int,outCh:Int,enc:Int,out:OutputStream){src.position(offset);src.limit(offset+size);val s=src.slice().order(ByteOrder.LITTLE_ENDIAN);if(enc==AudioFormat.ENCODING_PCM_16BIT&&inCh<=2&&inCh==outCh){val bytes=ByteArray(min(size,65536));while(s.hasRemaining()){val n=min(s.remaining(),bytes.size);s.get(bytes,0,n);out.write(bytes,0,n)};return};val data=ByteArray(16384);var p=0;fun emit(v:Int){val q=v.coerceIn(-32768,32767);if(p+2>data.size){out.write(data,0,p);p=0};data[p++]=(q and 255).toByte();data[p++]=((q shr 8)and 255).toByte()};if(enc==AudioFormat.ENCODING_PCM_FLOAT){val fs=s.asFloatBuffer();while(fs.remaining()>=inCh){var l=0f;var r=0f;for(c in 0 until inCh){val v=fs.get().coerceIn(-1f,1f);if(c==0)l=v;if(c==1)r=v};emit((l*32767).toInt());if(outCh>1)emit(((if(inCh>1)r else l)*32767).toInt())}}else{val ss=s.asShortBuffer();while(ss.remaining()>=inCh){var l=0;var r=0;for(c in 0 until inCh){val v=ss.get().toInt();if(c==0)l=v;if(c==1)r=v};emit(l);if(outCh>1)emit(if(inCh>1)r else l)}};if(p>0)out.write(data,0,p)}
 private fun encodePcmToAac(pcm:PCM,output:File,progress:(Int)->Unit){val f=MediaFormat.createAudioFormat(MediaFormat.MIMETYPE_AUDIO_AAC,pcm.rate,pcm.channels).apply{setInteger(MediaFormat.KEY_AAC_PROFILE,MediaCodecInfo.CodecProfileLevel.AACObjectLC);setInteger(MediaFormat.KEY_BIT_RATE,if(pcm.channels==1)128000 else 192000);setInteger(MediaFormat.KEY_MAX_INPUT_SIZE,32768)};val codec=MediaCodec.createEncoderByType(MediaFormat.MIMETYPE_AUDIO_AAC);var muxer:MediaMuxer?=null;var input:BufferedInputStream?=null
  try{codec.configure(f,null,null,MediaCodec.CONFIGURE_FLAG_ENCODE);codec.start();muxer=MediaMuxer(output.absolutePath,MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);input=BufferedInputStream(FileInputStream(pcm.file),262144);val info=MediaCodec.BufferInfo();val total=max(1L,pcm.file.length());var read=0L;var frames=0L;val bpf=pcm.channels*2;var inDone=false;var done=false;var track=-1;var started=false;var last=-1
   while(!done){if(!inDone){val i=codec.dequeueInputBuffer(10000);if(i>=0){val b=codec.getInputBuffer(i)!!;b.clear();var wanted=min(b.remaining(),32768);wanted-=wanted%bpf;val temp=ByteArray(wanted.coerceAtLeast(0));val n=if(wanted>0)input.read(temp)else -1;val pts=frames*1_000_000/pcm.rate;if(n<=0){codec.queueInputBuffer(i,0,0,pts,MediaCodec.BUFFER_FLAG_END_OF_STREAM);inDone=true}else{b.put(temp,0,n);codec.queueInputBuffer(i,0,n,pts,0);frames+=n/bpf;read+=n;val pp=(read*100/total).toInt().coerceIn(0,99);if(pp!=last){last=pp;progress(pp)}}}};when(val i=codec.dequeueOutputBuffer(info,10000)){MediaCodec.INFO_TRY_AGAIN_LATER->Unit;MediaCodec.INFO_OUTPUT_FORMAT_CHANGED->{if(!started){track=muxer.addTrack(codec.outputFormat);muxer.start();started=true}};else->if(i>=0){val b=codec.getOutputBuffer(i);if(b!=null&&info.size>0&&started&&(info.flags and MediaCodec.BUFFER_FLAG_CODEC_CONFIG)==0){b.position(info.offset);b.limit(info.offset+info.size);muxer.writeSampleData(track,b,info)};done=(info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM)!=0;codec.releaseOutputBuffer(i,false)}}};progress(100)
  }finally{runCatching{input?.close()};runCatching{codec.stop()};runCatching{codec.release()};runCatching{muxer?.stop()};runCatching{muxer?.release()}}
 }
 private fun mux(video:File,audio:File,output:File){val v=MediaExtractor();val a=MediaExtractor();var m:MediaMuxer?=null;try{v.setDataSource(video.absolutePath);a.setDataSource(audio.absolutePath);val vt=find(v,"video/");val at=find(a,"audio/");require(vt>=0&&at>=0);v.selectTrack(vt);a.selectTrack(at);m=MediaMuxer(output.absolutePath,MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);val ov=m.addTrack(v.getTrackFormat(vt));val oa=m.addTrack(a.getTrackFormat(at));m.start();val buf=ByteBuffer.allocateDirect(16*1024*1024);val info=MediaCodec.BufferInfo();var vd=false;var ad=false;while(!vd||!ad){val use=(if(!vd)v.sampleTime else Long.MAX_VALUE)<=(if(!ad)a.sampleTime else Long.MAX_VALUE);val ex=if(use)v else a;val track=if(use)ov else oa;buf.clear();val n=ex.readSampleData(buf,0);if(n<0){if(use)vd=true else ad=true}else{info.set(0,n,ex.sampleTime.coerceAtLeast(0),ex.sampleFlags);buf.position(0);buf.limit(n);m.writeSampleData(track,buf,info);ex.advance()}}}finally{runCatching{m?.stop()};runCatching{m?.release()};runCatching{v.release()};runCatching{a.release()}}}
 private fun find(e:MediaExtractor,p:String):Int{for(i in 0 until e.trackCount)if(e.getTrackFormat(i).getString(MediaFormat.KEY_MIME).orEmpty().startsWith(p))return i;return -1}
 private fun save(context:Context,file:File,spec:Spec):Uri{val(w,h)=spec.size;val q=when(spec.qualityIndex){2->"4K";1->"2K";else->"1080p"};val values=ContentValues().apply{put(MediaStore.Video.Media.DISPLAY_NAME,"NGS_Visualizer_${q}_${w}x${h}_${spec.fps}fps_${System.currentTimeMillis()}.mp4");put(MediaStore.Video.Media.MIME_TYPE,"video/mp4");put(MediaStore.Video.Media.RELATIVE_PATH,Environment.DIRECTORY_MOVIES+"/NGS Music Visualizer");put(MediaStore.Video.Media.IS_PENDING,1)};val r=context.contentResolver;val u=r.insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,values)?:error("Không tạo được file");try{r.openOutputStream(u,"w")!!.use{d->FileInputStream(file).use{it.copyTo(d,1024*1024)}};values.clear();values.put(MediaStore.Video.Media.IS_PENDING,0);r.update(u,values,null,null);return u}catch(e:Throwable){r.delete(u,null,null);throw e}}
}
