import jwt from 'jsonwebtoken';
import {APP_SECRET,q,verifyPassword,hashPassword,audit,newid} from './db.js';
export const safeUser=u=>({id:u.id,email:u.email,role:u.role,active:u.active,created_at:u.created_at});
export const norm=v=>String(v||'').trim().toLowerCase();
export async function auth(req,res,next){try{const t=req.cookies.ngs_session;if(!t)return res.status(401).json({error:'Chưa đăng nhập'});const p=jwt.verify(t,APP_SECRET,{issuer:'ngs-music-studio'}),r=await q('select * from users where id=$1 and active=true',[p.sub]);if(!r.rowCount)return res.status(401).json({error:'Phiên không hợp lệ'});req.user=r.rows[0];next()}catch{return res.status(401).json({error:'Phiên đã hết hạn'})}}
export const requireRole=(...roles)=>(req,res,next)=>roles.includes(req.user?.role)?next():res.status(403).json({error:'Không đủ quyền'});
export function registerAuthRoutes(app){
app.post('/api/auth/login',async(req,res)=>{const email=norm(req.body.email),pass=String(req.body.password||''),r=await q('select * from users where email=$1',[email]);if(!r.rowCount||!r.rows[0].active||!verifyPassword(pass,r.rows[0].salt,r.rows[0].password_hash)){await audit(null,'login_failed',email);return res.status(401).json({error:'Email hoặc mật khẩu không đúng'})}const u=r.rows[0],token=jwt.sign({sub:u.id,role:u.role,email:u.email},APP_SECRET,{expiresIn:'7d',issuer:'ngs-music-studio'});res.cookie('ngs_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});await audit(u.id,'login',u.id);res.json({user:safeUser(u)})});
app.post('/api/auth/logout',auth,async(req,res)=>{await audit(req.user.id,'logout',req.user.id);res.clearCookie('ngs_session');res.json({ok:true})});
app.get('/api/me',auth,(req,res)=>res.json({user:safeUser(req.user)}));
app.patch('/api/me',auth,async(req,res)=>{const sets=[],vals=[];if(req.body.email){vals.push(norm(req.body.email));sets.push(`email=$${vals.length}`)}if(req.body.password){if(String(req.body.password).length<10)return res.status(400).json({error:'Mật khẩu từ 10 ký tự'});const hp=hashPassword(req.body.password);vals.push(hp.hash);sets.push(`password_hash=$${vals.length}`);vals.push(hp.salt);sets.push(`salt=$${vals.length}`)}if(!sets.length)return res.json({user:safeUser(req.user)});vals.push(req.user.id);await q(`update users set ${sets.join(',')},updated_at=now() where id=$${vals.length}`,vals);const u=(await q('select * from users where id=$1',[req.user.id])).rows[0];res.json({user:safeUser(u)})});
app.get('/api/admin/users',auth,requireRole('SUPER_ADMIN'),async(_req,res)=>res.json({users:(await q('select id,email,role,active,created_at from users order by created_at')).rows}));
app.post('/api/admin/users',auth,requireRole('SUPER_ADMIN'),async(req,res)=>{const email=norm(req.body.email),pass=String(req.body.password||''),role=['ADMIN','USER'].includes(req.body.role)?req.body.role:'USER';if(!email||pass.length<10)return res.status(400).json({error:'Email và mật khẩu từ 10 ký tự'});const hp=hashPassword(pass),uid=newid();try{await q('insert into users(id,email,password_hash,salt,role,active,created_by,created_at,updated_at) values($1,$2,$3,$4,$5,true,$6,now(),now())',[uid,email,hp.hash,hp.salt,role,req.user.id]);await audit(req.user.id,'user_create',uid,{email,role});res.json({user:safeUser((await q('select * from users where id=$1',[uid])).rows[0])})}catch(e){res.status(400).json({error:e.code==='23505'?'Email đã tồn tại':e.message})}});
app.patch('/api/admin/users/:id',auth,requireRole('SUPER_ADMIN'),async(req,res)=>{const t=(await q('select * from users where id=$1',[req.params.id])).rows[0];if(!t)return res.status(404).json({error:'Không tìm thấy user'});if(t.role==='SUPER_ADMIN'&&t.id!==req.user.id)return res.status(403).json({error:'Không thể sửa SUPER_ADMIN khác'});const sets=[],vals=[];if(typeof req.body.active==='boolean'){if(t.id===req.user.id&&!req.body.active)return res.status(400).json({error:'Không thể tự khóa'});vals.push(req.body.active);sets.push(`active=$${vals.length}`)}if(req.body.role){if(t.id===req.user.id)return res.status(400).json({error:'Không thể tự hạ quyền'});const role=['ADMIN','USER'].includes(req.body.role)?req.body.role:null;if(!role)return res.status(400).json({error:'Role sai'});vals.push(role);sets.push(`role=$${vals.length}`)}if(req.body.password){const hp=hashPassword(req.body.password);vals.push(hp.hash);sets.push(`password_hash=$${vals.length}`);vals.push(hp.salt);sets.push(`salt=$${vals.length}`)}if(sets.length){vals.push(t.id);await q(`update users set ${sets.join(',')},updated_at=now() where id=$${vals.length}`,vals)}res.json({user:safeUser((await q('select * from users where id=$1',[t.id])).rows[0])})});
app.delete('/api/admin/users/:id',auth,requireRole('SUPER_ADMIN'),async(req,res)=>{if(req.params.id===req.user.id)return res.status(400).json({error:'Không thể tự xóa'});const t=(await q('select * from users where id=$1',[req.params.id])).rows[0];if(!t)return res.status(404).json({error:'Không tìm thấy'});if(t.role==='SUPER_ADMIN')return res.status(403).json({error:'Không thể xóa SUPER_ADMIN'});await q('delete from users where id=$1',[t.id]);res.json({ok:true})})}
