import fs from 'fs/promises';import path from 'path';import os from 'os';import {spawn} from 'child_process';import ffmpegPath from 'ffmpeg-static';import {q,newid} from './db.js';
export function normalizeSceneDurations(scenes,total){const src=scenes?.length?scenes:[{duration:total,text:'',motion:'slow_push',effect:'none'}],raw=src.map(s=>Math.max(2,Number(s.duration)||3)),sum=raw.reduce((a,b)=>a+b,0);let used=0;return src.map((s,i)=>{let d=i===src.length-1?Math.max(2,total-used):Math.max(2,Math.round(raw[i]/sum*total));used+=d;return{...s,duration:d}})}
function run(cmd,args){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:['ignore','pipe','pipe']});let err='';p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',c=>c===0?resolve():reject(new Error(`${cmd} exit ${c}: ${err.slice(-2500)}`)))})}
const ff=()=>process.env.FFMPEG_PATH||ffmpegPath||'ffmpeg';const esc=p=>p.replaceAll('\\','/').replaceAll(':','\\:').replaceAll("'","\\'");
export async function renderProject(project,plan,musicId,onProgress=async()=>{}){
  const tmp=await fs.mkdtemp(path.join(os.tmpdir(),`ngs-${project.id.slice(0,8)}-`));try{const scenes=normalizeSceneDurations(plan.scenes,project.duration),segs=[];
    for(let i=0;i<scenes.length;i++){const s=scenes[i],m=(await q('select * from media where id=$1',[s.imageId])).rows[0];if(!m)throw new Error(`Thiếu ảnh scene ${i+1}`);const img=path.join(tmp,`s${i}.jpg`),out=path.join(tmp,`v${i}.mp4`),txt=path.join(tmp,`t${i}.txt`);await fs.writeFile(img,m.data);await fs.writeFile(txt,String(s.text||''),'utf8');const dur=Number(s.duration),frames=Math.max(1,Math.round(dur*30)),zoom=s.motion==='pull_out'?`z='if(eq(on,1),1.08,max(zoom-0.0007,1.0))'`:`z='min(zoom+0.0007,1.08)'`;const filter=`[0:v]scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,gblur=sigma=28[bg];[0:v]scale=980:1680:force_original_aspect_ratio=decrease[fg];[bg][fg]overlay=(W-w)/2:(H-h)/2,zoompan=${zoom}:d=${frames}:s=1080x1920:fps=30,drawtext=textfile='${esc(txt)}':fontcolor=white:fontsize=54:borderw=3:bordercolor=black@0.65:x=(w-text_w)/2:y=h*0.76-text_h/2,fade=t=in:st=0:d=.18,fade=t=out:st=${Math.max(0,dur-.2)}:d=.2,format=yuv420p[v]`;await run(ff(),['-y','-loop','1','-t',String(dur),'-i',img,'-filter_complex',filter,'-map','[v]','-an','-r','30','-c:v','libx264','-preset','veryfast','-crf','21','-movflags','+faststart',out]);segs.push(out);await onProgress(70+Math.round((i+1)/scenes.length*15),`Đang dựng scene ${i+1}/${scenes.length}`)}
    const list=path.join(tmp,'concat.txt');await fs.writeFile(list,segs.map(x=>`file '${x.replaceAll("'","'\\''")}'`).join('\n'));const silent=path.join(tmp,'silent.mp4');await run(ff(),['-y','-f','concat','-safe','0','-i',list,'-c','copy',silent]);const final=path.join(tmp,'final.mp4');
    if(musicId){const m=(await q('select * from media where id=$1',[musicId])).rows[0];if(m){const mp=path.join(tmp,'music.bin');await fs.writeFile(mp,m.data);const fo=Math.max(0,project.duration-1.2);await run(ff(),['-y','-i',silent,'-stream_loop','-1','-i',mp,'-t',String(project.duration),'-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','192k','-af',`loudnorm=I=-14:TP=-1.5:LRA=11,afade=t=in:st=0:d=.5,afade=t=out:st=${fo}:d=1.2`,'-movflags','+faststart',final])}else await fs.copyFile(silent,final)}else await fs.copyFile(silent,final);const data=await fs.readFile(final),outId=newid();await q('insert into media(id,owner_id,kind,name,mime,data,meta,shared,created_at) values($1,$2,$3,$4,$5,$6,$7,true,now())',[outId,project.owner_id,'video',`${plan.title||project.id}.mp4`,'video/mp4',data,{generatedBy:'ffmpeg',projectId:project.id}]);return outId
  }finally{await fs.rm(tmp,{recursive:true,force:true}).catch(()=>{})}}
