import express from 'express';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import path from 'path';
import {fileURLToPath} from 'url';
import {pool,q,initDb,getSetting,setSetting,newid,audit} from './db.js';
import {auth,requireRole,registerAuthRoutes} from './auth.js';
import {copilotPlan,saveGeneratedImage} from './providers.js';
import {normalizeSceneDurations,renderProject} from './render.js';

const __dirname=path.dirname(fileURLToPath(import.meta.url)),ROOT=path.resolve(__dirname,'..'),PORT=Number(process.env.PORT||3000),app=express();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:35*1024*1024}});
app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));app.use(cookieParser());app.use(express.static(path.join(ROOT,'public')));registerAuthRoutes(app);

async function updateProject(id,patch){const ks=Object.keys(patch),vals=[],sets=[];for(const k of ks){vals.push(patch[k]);sets.push(`${k}=$${vals.length}`)}if(!sets.length)return;vals.push(id);await q(`update projects set ${sets.join(',')},updated_at=now() where id=$${vals.length}`,vals)}
app.get('/api/health',async(_req,res)=>{let db=false;try{if(pool){await q('select 1');db=true}}catch{}let providers={copilot:false,cloudflare:false};if(db){try{providers.copilot=!!(await getSetting('copilot_token'));providers.cloudflare=!!((await getSetting('cf_account_id'))&&(await getSetting('cf_api_token')))}catch{}}res.json({ok:true,version:'7.0.0-online',db,providers})});

app.get('/api/settings',auth,requireRole('SUPER_ADMIN'),async(_req,res)=>{const keys=['copilot_token','copilot_model','cf_account_id','cf_api_token','image_daily_limit','premium_fallback'],out={};for(const k of keys){const v=await getSetting(k).catch(()=> '');out[k]=(k.includes('token')||k.includes('api_')||k==='cf_account_id')?!!v:v}res.json({settings:out})});
app.post('/api/settings',auth,requireRole('SUPER_ADMIN'),async(req,res)=>{const b=req.body||{};if(b.copilot_token)await setSetting('copilot_token',b.copilot_token,true);if(b.copilot_model)await setSetting('copilot_model',b.copilot_model,false);if(b.cf_account_id)await setSetting('cf_account_id',b.cf_account_id,true);if(b.cf_api_token)await setSetting('cf_api_token',b.cf_api_token,true);if(b.image_daily_limit!==undefined)await setSetting('image_daily_limit',String(Math.max(1,Math.min(100,Number(b.image_daily_limit)||20))),false);if(b.premium_fallback!==undefined)await setSetting('premium_fallback',String(!!b.premium_fallback),false);await audit(req.user.id,'settings_update','providers',{keys:Object.keys(b)});res.json({ok:true})});

app.post('/api/media',auth,upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Thiếu file'});const kind=String(req.body.kind||'image');if(!['music','image','logo','video'].includes(kind))return res.status(400).json({error:'Loại media không hợp lệ'});const id=newid();await q('insert into media(id,owner_id,kind,name,mime,data,meta,shared,created_at) values($1,$2,$3,$4,$5,$6,$7,true,now())',[id,req.user.id,kind,req.file.originalname,req.file.mimetype||'application/octet-stream',req.file.buffer,{}]);res.json({media:{id,kind,name:req.file.originalname,mime:req.file.mimetype,size:req.file.size}})});
app.get('/api/media',auth,async(req,res)=>{const k=req.query.kind?String(req.query.kind):null,r=k?await q('select id,owner_id,kind,name,mime,meta,shared,created_at,octet_length(data) size from media where kind=$1 order by created_at desc',[k]):await q('select id,owner_id,kind,name,mime,meta,shared,created_at,octet_length(data) size from media order by created_at desc');res.json({media:r.rows})});
app.get('/api/media/:id',auth,async(req,res)=>{const r=await q('select * from media where id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).end();res.setHeader('Content-Type',r.rows[0].mime);res.setHeader('Cache-Control','private,max-age=3600');res.send(r.rows[0].data)});
app.delete('/api/media/:id',auth,async(req,res)=>{const m=(await q('select * from media where id=$1',[req.params.id])).rows[0];if(!m)return res.status(404).json({error:'Không tìm thấy'});if(req.user.role!=='SUPER_ADMIN'&&m.owner_id!==req.user.id)return res.status(403).json({error:'Không đủ quyền'});await q('delete from media where id=$1',[m.id]);res.json({ok:true})});

let queue=Promise.resolve();const enqueue=fn=>(queue=queue.then(fn).catch(e=>console.error('queue',e)));
async function processProject(pid){try{const p=(await q('select * from projects where id=$1',[pid])).rows[0];if(!p)return;await updateProject(pid,{status:'planning',progress:8,message:'Copilot đang lập kế hoạch',error:null});const recent=(await q('select title,idea,status,created_at from projects where id<>$1 order by created_at desc limit 12',[pid])).rows,music=(await q("select id,name,meta from media where kind='music' order by created_at desc limit 100")).rows,plan=await copilotPlan(p,recent,music);plan.scenes=normalizeSceneDurations(plan.scenes,p.duration);await updateProject(pid,{title:plan.title||p.title,plan,status:'visuals',progress:20,message:`Đang tạo ${plan.scenes.length} ảnh bằng Cloudflare FLUX`});for(let i=0;i<plan.scenes.length;i++){plan.scenes[i].imageId=await saveGeneratedImage(p.owner_id,pid,i,plan.scenes[i].imagePrompt);await updateProject(pid,{plan,progress:20+Math.round((i+1)/plan.scenes.length*40),message:`Đã tạo ảnh ${i+1}/${plan.scenes.length}`})}let musicId=null;if(p.music_mode==='auto'){const ids=new Set(music.map(x=>x.id));musicId=plan.musicId&&ids.has(plan.musicId)?plan.musicId:(music[0]?.id||null)}if(!musicId){await updateProject(pid,{plan,status:'waiting_music',progress:62,message:'Visual đã xong — đang chờ chọn nhạc'});return}await updateProject(pid,{plan,music_id:musicId,status:'rendering',progress:68,message:'FFmpeg đang dựng video'});const out=await renderProject(p,plan,musicId,(progress,message)=>updateProject(pid,{progress,message}));await updateProject(pid,{output_media_id:out,status:'done',progress:100,message:'Video hoàn thành'})}catch(e){console.error(e);await updateProject(pid,{status:'error',progress:0,message:'Có lỗi',error:String(e.message||e)}).catch(()=>{})}}

app.post('/api/projects',auth,async(req,res)=>{const pid=newid(),idea=String(req.body.idea||'').slice(0,3000),duration=[15,20,30,45,60].includes(Number(req.body.duration))?Number(req.body.duration):20,mode=req.body.music_mode==='manual'?'manual':'auto';await q('insert into projects(id,owner_id,title,idea,duration,music_mode,status,progress,message,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,0,$8,now(),now())',[pid,req.user.id,'Video mới',idea,duration,mode,'queued','Đã xếp hàng']);enqueue(()=>processProject(pid));res.status(202).json({project:{id:pid,status:'queued'}})});
app.get('/api/projects',auth,async(req,res)=>{const r=req.user.role==='SUPER_ADMIN'?await q('select * from projects order by created_at desc limit 100'):await q('select * from projects where owner_id=$1 order by created_at desc limit 100',[req.user.id]);res.json({projects:r.rows})});
app.get('/api/projects/:id',auth,async(req,res)=>{const p=(await q('select * from projects where id=$1',[req.params.id])).rows[0];if(!p)return res.status(404).json({error:'Không tìm thấy project'});if(req.user.role!=='SUPER_ADMIN'&&p.owner_id!==req.user.id)return res.status(403).json({error:'Không đủ quyền'});res.json({project:p})});
app.post('/api/projects/:id/music',auth,async(req,res)=>{const p=(await q('select * from projects where id=$1',[req.params.id])).rows[0];if(!p)return res.status(404).json({error:'Không tìm thấy project'});if(req.user.role!=='SUPER_ADMIN'&&p.owner_id!==req.user.id)return res.status(403).json({error:'Không đủ quyền'});const m=(await q("select * from media where id=$1 and kind='music'",[req.body.musicId])).rows[0];if(!m)return res.status(400).json({error:'Nhạc không hợp lệ'});await updateProject(p.id,{music_id:m.id,status:'rendering',progress:68,message:'Đã chọn nhạc — đang render'});enqueue(async()=>{try{const latest=(await q('select * from projects where id=$1',[p.id])).rows[0],out=await renderProject(latest,latest.plan,m.id,(progress,message)=>updateProject(p.id,{progress,message}));await updateProject(p.id,{output_media_id:out,status:'done',progress:100,message:'Video hoàn thành'})}catch(e){await updateProject(p.id,{status:'error',error:e.message,message:'Render lỗi'})}});res.json({ok:true})});
app.post('/api/projects/:id/retry',auth,async(req,res)=>{const p=(await q('select * from projects where id=$1',[req.params.id])).rows[0];if(!p)return res.status(404).json({error:'Không tìm thấy'});if(req.user.role!=='SUPER_ADMIN'&&p.owner_id!==req.user.id)return res.status(403).json({error:'Không đủ quyền'});await updateProject(p.id,{status:'queued',progress:0,error:null,message:'Đã xếp hàng lại'});enqueue(()=>processProject(p.id));res.json({ok:true})});

app.get('*',(_req,res)=>res.sendFile(path.join(ROOT,'public','index.html')));
initDb().then(()=>app.listen(PORT,()=>console.log(`NGS V7 :${PORT}`))).catch(e=>{console.error(e);app.listen(PORT,()=>console.log(`NGS V7 no-db :${PORT}`))});
